image:
  file: .gitpod.Dockerfile 

ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 3337
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - graphql.vscode-graphql-syntax
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

tasks:
- init: "/app/entrypoint.sh"